name: 'Testing setup terraform'

on:
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  terraform-run-local:
    name: 'Terraform test'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash
        working-directory: ./.github/workflows/data/local
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@bb87bf54b80b50581aae1cb56eeb822eaef1d5d3
      with:
        terraform_wrapper: true

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Output the pet name
      run: terraform output -json


  terraform-run-local-no-wrapper:
    name: 'Terraform test'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash
        working-directory: ./.github/workflows/data/local
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@bb87bf54b80b50581aae1cb56eeb822eaef1d5d3
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Output the pet name
      run: terraform output -json
